-- Purpose:
-- Defines reporting-ready views for campaign performance analysis.
--
-- These views combine campaign metadata, paid media spend, lead activity,
-- and monthly budget data into analyst-friendly outputs.


CREATE SCHEMA IF NOT EXISTS EXAMPLE.ANALYTICS;

CREATE OR REPLACE VIEW EXAMPLE.ANALYTICS.DIM_CAMPAIGN_METADATA AS
SELECT
    MD5(
        UPPER(COALESCE(NAMING_CONVENTION, '')) || '|' ||
        UPPER(COALESCE(PLATFORM, '')) || '|' ||
        COALESCE(TO_VARCHAR(LAUNCH_DATE), '') || '|' ||
        COALESCE(TO_VARCHAR(END_DATE), '')
    ) AS CAMPAIGN_METADATA_KEY,

    NAMING_CONVENTION AS CAMPAIGN_NAME,
    UPPER(NAMING_CONVENTION) AS CAMPAIGN_NAME_NORM,

    PLATFORM,
    UPPER(PLATFORM) AS PLATFORM_NORM,

    LAUNCH_DATE,
    END_DATE,

    STATUS AS TRACKER_STATUS,
    OWNER,
    PRIORITY,

    DATASOURCE,
    DATASOURCE_SHEET,
    LOAD_DATE

FROM EXAMPLE.STG.STG_CAMPAIGN_TRACKER;


CREATE OR REPLACE VIEW EXAMPLE.ANALYTICS.FCT_PAID_MEDIA_DAILY AS
SELECT
    PM."DATE",
    DATE_TRUNC('MONTH', PM."DATE")::DATE AS REPORT_MONTH,

    PM.CLIENT,
    UPPER(PM.CLIENT) AS CLIENT_NORM,

    PM.CAMPAIGN_NAME,
    UPPER(PM.CAMPAIGN_NAME) AS CAMPAIGN_NAME_NORM,

    PM.PLATFORM,
    UPPER(PM.PLATFORM) AS PLATFORM_NORM,

    PM.SPEND,
    PM.IMPRESSIONS,
    PM.CLICKS,

    PM.CTR_REPORTED,
    PM.CTR_CALCULATED,

    CASE
        WHEN PM.CLICKS > 0 THEN PM.SPEND / PM.CLICKS
        ELSE NULL
    END AS CPC,

    CASE
        WHEN PM.IMPRESSIONS > 0 THEN PM.SPEND / PM.IMPRESSIONS * 1000
        ELSE NULL
    END AS CPM,

    CASE
        WHEN PM.SPEND < 0 THEN TRUE
        WHEN PM.IMPRESSIONS < 0 THEN TRUE
        WHEN PM.CLICKS < 0 THEN TRUE
        WHEN PM.CLICKS > PM.IMPRESSIONS THEN TRUE
        ELSE FALSE
    END AS HAS_METRIC_ISSUE,

    PM.STATUS AS SOURCE_STATUS,

    CM.TRACKER_STATUS,
    CM.OWNER,
    CM.PRIORITY,

    PM.DATASOURCE,
    PM.DATASOURCE_SHEET,
    PM.LOAD_DATE

FROM EXAMPLE.STG.STG_PAID_MEDIA PM

LEFT JOIN EXAMPLE.ANALYTICS.DIM_CAMPAIGN_METADATA CM
    ON UPPER(PM.CAMPAIGN_NAME) = CM.CAMPAIGN_NAME_NORM
    AND UPPER(PM.PLATFORM) = CM.PLATFORM_NORM
    AND PM."DATE" BETWEEN CM.LAUNCH_DATE AND CM.END_DATE;



CREATE OR REPLACE VIEW EXAMPLE.ANALYTICS.FCT_LEADS_DAILY AS
SELECT
    LEAD_DATE,
    DATE_TRUNC('MONTH', LEAD_DATE)::DATE AS LEAD_MONTH,

    CLIENT,
    UPPER(CLIENT) AS CLIENT_NORM,

    SOURCE,
    UPPER(SOURCE) AS SOURCE_NORM,

    SOURCE2,
    UPPER(SOURCE2) AS SOURCE2_NORM,

    COUNT(*) AS LEAD_COUNT,

    SUM(
        CASE
            WHEN IS_QUALIFIED = TRUE THEN 1
            ELSE 0
        END
    ) AS QUALIFIED_LEAD_COUNT,

    SUM(REVENUE_ESTIMATE) AS ESTIMATED_REVENUE,

    AVG(REVENUE_ESTIMATE) AS AVG_REVENUE_ESTIMATE,

    DATASOURCE,
    DATASOURCE_SHEET,
    MAX(LOAD_DATE) AS MAX_LOAD_DATE

FROM EXAMPLE.STG.STG_LEADS

GROUP BY
    LEAD_DATE,
    DATE_TRUNC('MONTH', LEAD_DATE)::DATE,
    CLIENT,
    UPPER(CLIENT),
    SOURCE,
    UPPER(SOURCE),
    SOURCE2,
    UPPER(SOURCE2),
    DATASOURCE,
    DATASOURCE_SHEET;


CREATE OR REPLACE VIEW EXAMPLE.ANALYTICS.FCT_MONTHLY_BUDGET AS
SELECT
    BUDGET_MONTH,

    CLIENT,
    UPPER(CLIENT) AS CLIENT_NORM,

    FISCAL_YEAR,

    CAMPAIGN,
    UPPER(CAMPAIGN) AS CAMPAIGN_NORM,

    LAUNCH_DATE,
    END_DATE,

    GROSS_BUDGET,
    MONTHLY_BUDGET,

    DATASOURCE,
    DATASOURCE_SHEET,
    LOAD_DATE

FROM EXAMPLE.STG.STG_MONTHLY_BUDGET;



CREATE OR REPLACE VIEW EXAMPLE.ANALYTICS.MART_CLIENT_MONTHLY_FUNNEL AS
WITH PAID AS (
    SELECT
        REPORT_MONTH,
        CLIENT,
        CLIENT_NORM,

        SUM(SPEND) AS TOTAL_SPEND,
        SUM(IMPRESSIONS) AS TOTAL_IMPRESSIONS,
        SUM(CLICKS) AS TOTAL_CLICKS,

        CASE
            WHEN SUM(IMPRESSIONS) > 0 THEN SUM(CLICKS) / SUM(IMPRESSIONS)::FLOAT
            ELSE NULL
        END AS CTR,

        CASE
            WHEN SUM(CLICKS) > 0 THEN SUM(SPEND) / SUM(CLICKS)
            ELSE NULL
        END AS CPC,

        CASE
            WHEN SUM(IMPRESSIONS) > 0 THEN SUM(SPEND) / SUM(IMPRESSIONS) * 1000
            ELSE NULL
        END AS CPM

    FROM EXAMPLE.ANALYTICS.FCT_PAID_MEDIA_DAILY

    GROUP BY
        REPORT_MONTH,
        CLIENT,
        CLIENT_NORM
),

LEADS AS (
    SELECT
        LEAD_MONTH,
        CLIENT,
        CLIENT_NORM,

        SUM(LEAD_COUNT) AS TOTAL_LEADS,
        SUM(QUALIFIED_LEAD_COUNT) AS QUALIFIED_LEADS,
        SUM(ESTIMATED_REVENUE) AS ESTIMATED_REVENUE

    FROM EXAMPLE.ANALYTICS.FCT_LEADS_DAILY

    GROUP BY
        LEAD_MONTH,
        CLIENT,
        CLIENT_NORM
)

SELECT
    COALESCE(P.REPORT_MONTH, L.LEAD_MONTH) AS REPORT_MONTH,

    COALESCE(P.CLIENT, L.CLIENT) AS CLIENT,
    COALESCE(P.CLIENT_NORM, L.CLIENT_NORM) AS CLIENT_NORM,

    COALESCE(P.TOTAL_SPEND, 0) AS TOTAL_SPEND,
    COALESCE(P.TOTAL_IMPRESSIONS, 0) AS TOTAL_IMPRESSIONS,
    COALESCE(P.TOTAL_CLICKS, 0) AS TOTAL_CLICKS,

    COALESCE(L.TOTAL_LEADS, 0) AS TOTAL_LEADS,
    COALESCE(L.QUALIFIED_LEADS, 0) AS QUALIFIED_LEADS,
    COALESCE(L.ESTIMATED_REVENUE, 0) AS ESTIMATED_REVENUE,

    P.CTR,
    P.CPC,
    P.CPM,

    CASE
        WHEN COALESCE(L.TOTAL_LEADS, 0) > 0
            THEN COALESCE(P.TOTAL_SPEND, 0) / L.TOTAL_LEADS
        ELSE NULL
    END AS COST_PER_LEAD,

    CASE
        WHEN COALESCE(L.QUALIFIED_LEADS, 0) > 0
            THEN COALESCE(P.TOTAL_SPEND, 0) / L.QUALIFIED_LEADS
        ELSE NULL
    END AS COST_PER_QUALIFIED_LEAD,

    CASE
        WHEN COALESCE(P.TOTAL_SPEND, 0) > 0
            THEN COALESCE(L.ESTIMATED_REVENUE, 0) / P.TOTAL_SPEND
        ELSE NULL
    END AS ESTIMATED_ROAS,

    CASE
        WHEN P.TOTAL_SPEND IS NULL THEN 'LEADS_WITHOUT_SPEND'
        WHEN L.TOTAL_LEADS IS NULL THEN 'SPEND_WITHOUT_LEADS'
        ELSE 'MATCHED'
    END AS MATCH_STATUS

FROM PAID P

FULL OUTER JOIN LEADS L
    ON P.CLIENT_NORM = L.CLIENT_NORM
    AND P.REPORT_MONTH = L.LEAD_MONTH;


-- Manually maintained mapping table used to reconcile messy paid media campaign names to governed campaign/budget categories.
CREATE TABLE IF NOT EXISTS EXAMPLE.ANALYTICS.DIM_CAMPAIGN_MAP (
    CLIENT VARCHAR,
    CAMPAIGN VARCHAR,
    CAMPAIGN_NAME VARCHAR,
    PLATFORM VARCHAR,

    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    NOTES VARCHAR,

    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);






CREATE OR REPLACE VIEW EXAMPLE.ANALYTICS.MART_CLIENT_MONTHLY_SPEND_VS_BUDGET AS

WITH MONTHLY_SPEND AS (
    SELECT
        PM.REPORT_MONTH,
        PM.CLIENT,
        UPPER(MAP.CAMPAIGN) AS CAMPAIGN,

        LISTAGG(DISTINCT PM.CAMPAIGN_NAME, ', ') 
            WITHIN GROUP (ORDER BY PM.CAMPAIGN_NAME) AS CAMPAIGN_NAME,

        SUM(PM.SPEND) AS TOTAL_SPEND,
        SUM(PM.IMPRESSIONS) AS TOTAL_IMPRESSIONS,
        SUM(PM.CLICKS) AS TOTAL_CLICKS,

        CASE
            WHEN SUM(PM.IMPRESSIONS) > 0 
                THEN SUM(PM.CLICKS) / SUM(PM.IMPRESSIONS)::FLOAT
            ELSE NULL
        END AS CTR,

        CASE
            WHEN SUM(PM.CLICKS) > 0 
                THEN SUM(PM.SPEND) / SUM(PM.CLICKS)
            ELSE NULL
        END AS CPC,

        CASE
            WHEN SUM(PM.IMPRESSIONS) > 0 
                THEN SUM(PM.SPEND) / SUM(PM.IMPRESSIONS) * 1000
            ELSE NULL
        END AS CPM,

        CASE
            WHEN UPPER(MAP.CAMPAIGN) IS NULL THEN TRUE
            ELSE FALSE
        END AS HAS_UNMAPPED_CAMPAIGN

    FROM EXAMPLE.ANALYTICS.FCT_PAID_MEDIA_DAILY PM

LEFT JOIN EXAMPLE.ANALYTICS.DIM_CAMPAIGN_MAP MAP
    ON UPPER(TRIM(PM.CAMPAIGN_NAME)) = UPPER(TRIM(MAP.CAMPAIGN_NAME))
    AND MAP.IS_ACTIVE = TRUE

    GROUP BY
        PM.REPORT_MONTH,
        PM.CLIENT,
        MAP.CAMPAIGN
),

MONTHLY_BUDGET AS (
    SELECT
        BUDGET_MONTH,
        CLIENT,
        CAMPAIGN,

        SUM(MONTHLY_BUDGET) AS MONTHLY_BUDGET,
        MAX(GROSS_BUDGET) AS GROSS_BUDGET

    FROM EXAMPLE.ANALYTICS.FCT_MONTHLY_BUDGET

    GROUP BY
        BUDGET_MONTH,
        CLIENT,
        CAMPAIGN
)

SELECT
    COALESCE(S.REPORT_MONTH, B.BUDGET_MONTH) AS REPORT_MONTH,

    COALESCE(S.CLIENT, B.CLIENT) AS CLIENT,
    COALESCE(S.CAMPAIGN, B.CAMPAIGN) AS CAMPAIGN,

    S.CAMPAIGN_NAME,

    COALESCE(S.TOTAL_SPEND, 0) AS TOTAL_SPEND,
    COALESCE(B.MONTHLY_BUDGET, 0) AS MONTHLY_BUDGET,

    COALESCE(B.MONTHLY_BUDGET, 0) - COALESCE(S.TOTAL_SPEND, 0) AS BUDGET_REMAINING,

    CASE
        WHEN COALESCE(B.MONTHLY_BUDGET, 0) > 0
            THEN COALESCE(S.TOTAL_SPEND, 0) / B.MONTHLY_BUDGET
        ELSE NULL
    END AS BUDGET_UTILIZATION_RATE,

    S.TOTAL_IMPRESSIONS,
    S.TOTAL_CLICKS,
    S.CTR,
    S.CPC,
    S.CPM,

    CASE
        WHEN S.HAS_UNMAPPED_CAMPAIGN = TRUE THEN 'UNMAPPED_CAMPAIGN'
        WHEN B.MONTHLY_BUDGET IS NULL THEN 'NO_BUDGET_FOUND'
        WHEN S.TOTAL_SPEND IS NULL THEN 'NO_SPEND_FOUND'
        WHEN S.TOTAL_SPEND > B.MONTHLY_BUDGET THEN 'OVER_BUDGET'
        WHEN S.TOTAL_SPEND >= B.MONTHLY_BUDGET * 0.9 THEN 'NEAR_BUDGET'
        ELSE 'OK'
    END AS BUDGET_STATUS

FROM MONTHLY_SPEND S

FULL OUTER JOIN MONTHLY_BUDGET B
    ON S.CLIENT = B.CLIENT
    AND S.CAMPAIGN = B.CAMPAIGN
    AND S.REPORT_MONTH = B.BUDGET_MONTH;


-- Data quality view: identifies paid media campaign names that have not yet been mapped to governed campaign/budget categories.
CREATE OR REPLACE VIEW EXAMPLE.ANALYTICS.UNMAPPED_PAID_MEDIA_CAMPAIGNS AS
SELECT
    PM.CLIENT,
    PM.CAMPAIGN_NAME,
    PM.PLATFORM,
    MIN(PM."DATE") AS FIRST_SEEN_DATE,
    MAX(PM."DATE") AS LAST_SEEN_DATE,
    SUM(PM.SPEND) AS TOTAL_SPEND
FROM EXAMPLE.ANALYTICS.FCT_PAID_MEDIA_DAILY PM

LEFT JOIN EXAMPLE.ANALYTICS.DIM_CAMPAIGN_MAP MAP
    ON UPPER(TRIM(PM.CAMPAIGN_NAME)) = UPPER(TRIM(MAP.CAMPAIGN_NAME))
    AND MAP.IS_ACTIVE = TRUE

WHERE MAP.CAMPAIGN_NAME IS NULL

GROUP BY
    PM.CLIENT,
    PM.CAMPAIGN_NAME,
    PM.PLATFORM;





INSERT INTO EXAMPLE.ANALYTICS.DIM_CAMPAIGN_MAP (
    CLIENT,
    CAMPAIGN,
    CAMPAIGN_NAME,
    PLATFORM,
    IS_ACTIVE
)
VALUES
    ('BEACON CLINIC', 'Retargeting Q1', 'BEACON_TIKTOK_Retargeting_Q1', 'TikTok', TRUE),
    ('Northstar Labs', 'Competitor Q1', 'NORTHSTAR_YOUTUBE_Competitor_Q1', 'YouTube', TRUE),
    ('Orion Dental', 'Remarketing Q1', 'ORION_GOOGLEADS_Remarketing_Q1', 'Google Ads', TRUE),
    ('Luna Pediatrics', 'Awareness Q1', 'LUNA_TIKTOK_Awareness_Q1', 'TikTok', TRUE);
