-- Purpose:
-- Defines cleaned staging views over RAW tables.
--
-- STG views standardize column naming, apply light type cleanup, and document
-- business assumptions before data is used by analytics views.
--
-- NOTES intentionally left out - retained in RAW only
-- CAMPAIGN_NAME is intended to act as a unique business key; the sample data intentionally includes exceptions to demonstrate data quality checks.

CREATE SCHEMA IF NOT EXISTS EXAMPLE.STG;


CREATE OR REPLACE VIEW EXAMPLE.STG.STG_CAMPAIGN_TRACKER AS
SELECT
    LAUNCH_DATE,
    END_DATE,

    UPPER(NULLIF(TRIM(NAMING_CONVENTION), '')) AS NAMING_CONVENTION,
    UPPER(NULLIF(TRIM(PLATFORM), '')) AS PLATFORM,
    UPPER(NULLIF(TRIM(STATUS), '')) AS STATUS,
    UPPER(NULLIF(TRIM(OWNER), '')) AS OWNER,
    UPPER(NULLIF(TRIM(PRIORITY), '')) AS PRIORITY,

    NULLIF(TRIM(DATASOURCE), '') AS DATASOURCE,
    NULLIF(TRIM(DATASOURCE_SHEET), '') AS DATASOURCE_SHEET,
    LOAD_DATE

FROM EXAMPLE.RAW.CAMPAIGN_TRACKER_RAW

QUALIFY ROW_NUMBER() OVER (
    PARTITION BY
        LAUNCH_DATE,
        END_DATE,
        NAMING_CONVENTION,
        PLATFORM,
        DATASOURCE_SHEET
    ORDER BY LOAD_DATE DESC
) = 1;



CREATE OR REPLACE VIEW EXAMPLE.STG.STG_LEADS AS
SELECT
    LEAD_DATE,

    UPPER(NULLIF(TRIM(CLIENT), '')) AS CLIENT,
    UPPER(NULLIF(TRIM(FIRST_NAME), '')) AS FIRST_NAME,
    UPPER(NULLIF(TRIM(LAST_NAME), '')) AS LAST_NAME,

    UPPER(NULLIF(TRIM(EMAIL), '')) AS EMAIL,

    REGEXP_REPLACE(NULLIF(TRIM(PHONE), ''), '[^0-9]', '') AS PHONE_DIGITS,

    UPPER(NULLIF(TRIM(SOURCE), '')) AS SOURCE,
    UPPER(NULLIF(TRIM(SOURCE2), '')) AS SOURCE2,

    CASE
        WHEN LOWER(TRIM(QUALIFIED)) IN ('yes', 'y', 'true', '1', 'qualified') THEN TRUE
        WHEN LOWER(TRIM(QUALIFIED)) IN ('no', 'n', 'false', '0', 'not qualified', 'unqualified') THEN FALSE
        ELSE NULL
    END AS IS_QUALIFIED,

    REVENUE_ESTIMATE AS REVENUE_ESTIMATE,

    UPPER(NULLIF(TRIM(ADDRESS), '')) AS ADDRESS,

    NULLIF(TRIM(DATASOURCE), '') AS DATASOURCE,
    NULLIF(TRIM(DATASOURCE_SHEET), '') AS DATASOURCE_SHEET,
    LOAD_DATE

FROM EXAMPLE.RAW.LEADS_RAW

QUALIFY ROW_NUMBER() OVER (
    PARTITION BY
        LEAD_DATE,
        CLIENT,
        UPPER(NULLIF(TRIM(EMAIL), '')),
        REGEXP_REPLACE(NULLIF(TRIM(PHONE), ''), '[^0-9]', '')
    ORDER BY LOAD_DATE DESC
) = 1;



CREATE OR REPLACE VIEW EXAMPLE.STG.STG_PAID_MEDIA AS
SELECT
    "DATE" AS "DATE",

    UPPER(NULLIF(TRIM(CLIENT), '')) AS CLIENT,
    UPPER(NULLIF(TRIM(CAMPAIGN_NAME), '')) AS CAMPAIGN_NAME,
    UPPER(NULLIF(TRIM(PLATFORM), '')) AS PLATFORM,

    SPEND AS SPEND,

    IMPRESSIONS AS IMPRESSIONS,
    CLICKS AS CLICKS,

    (CTR/100)::FLOAT AS CTR_REPORTED,

    CASE
        WHEN IMPRESSIONS > 0 THEN CLICKS / IMPRESSIONS::FLOAT
        ELSE NULL
    END AS CTR_CALCULATED,

    UPPER(NULLIF(TRIM(STATUS), '')) AS STATUS,

    NULLIF(TRIM(DATASOURCE), '') AS DATASOURCE,
    NULLIF(TRIM(DATASOURCE_SHEET), '') AS DATASOURCE_SHEET,
    LOAD_DATE

FROM EXAMPLE.RAW.PAID_MEDIA_RAW

QUALIFY ROW_NUMBER() OVER (
    PARTITION BY
        "DATE",
        CLIENT,
        CAMPAIGN_NAME,
        PLATFORM,
        DATASOURCE_SHEET
    ORDER BY LOAD_DATE DESC
) = 1;


CREATE OR REPLACE VIEW EXAMPLE.STG.STG_MONTHLY_BUDGET_WIDE AS
SELECT
    UPPER(NULLIF(TRIM(CLIENT), '')) AS CLIENT,
    FISCAL_YEAR AS FISCAL_YEAR,
    UPPER(NULLIF(TRIM(CAMPAIGN), '')) AS CAMPAIGN,

    LAUNCH_DATE,
    END_DATE,

    GROSS_BUDGET AS GROSS_BUDGET,

    JAN AS JAN,
    FEB AS FEB,
    MAR AS MAR,
    APR AS APR,
    MAY AS MAY,
    JUN AS JUN,
    JUL AS JUL,
    AUG AS AUG,
    SEP AS SEP,
    OCT AS OCT,
    NOV AS NOV,
    DEC AS DEC,

    NULLIF(TRIM(DATASOURCE), '') AS DATASOURCE,
    NULLIF(TRIM(DATASOURCE_SHEET), '') AS DATASOURCE_SHEET,
    LOAD_DATE

FROM EXAMPLE.RAW.MONTHLY_BUDGET_RAW

QUALIFY ROW_NUMBER() OVER (
    PARTITION BY
        CLIENT,
        FISCAL_YEAR,
        CAMPAIGN,
        LAUNCH_DATE,
        END_DATE,
        DATASOURCE_SHEET
    ORDER BY LOAD_DATE DESC
) = 1;




CREATE OR REPLACE VIEW EXAMPLE.STG.STG_MONTHLY_BUDGET AS
SELECT
    UPPER(CLIENT) AS CLIENT,
    FISCAL_YEAR AS FISCAL_YEAR,
    UPPER(CAMPAIGN) AS CAMPAIGN,
    LAUNCH_DATE AS LAUNCH_DATE,
    END_DATE AS END_DATE,
    GROSS_BUDGET AS GROSS_BUDGET,

    MONTH_NAME AS MONTH_NAME,

    CASE MONTH_NAME
        WHEN 'JAN' THEN 1
        WHEN 'FEB' THEN 2
        WHEN 'MAR' THEN 3
        WHEN 'APR' THEN 4
        WHEN 'MAY' THEN 5
        WHEN 'JUN' THEN 6
        WHEN 'JUL' THEN 7
        WHEN 'AUG' THEN 8
        WHEN 'SEP' THEN 9
        WHEN 'OCT' THEN 10
        WHEN 'NOV' THEN 11
        WHEN 'DEC' THEN 12
    END AS MONTH_NUM,

    TO_DATE(
        FISCAL_YEAR || '-' ||
        LPAD(
            CASE MONTH_NAME
                WHEN 'JAN' THEN 1
                WHEN 'FEB' THEN 2
                WHEN 'MAR' THEN 3
                WHEN 'APR' THEN 4
                WHEN 'MAY' THEN 5
                WHEN 'JUN' THEN 6
                WHEN 'JUL' THEN 7
                WHEN 'AUG' THEN 8
                WHEN 'SEP' THEN 9
                WHEN 'OCT' THEN 10
                WHEN 'NOV' THEN 11
                WHEN 'DEC' THEN 12
            END,
            2,
            '0'
        ) || '-01'
    ) AS BUDGET_MONTH,

    MONTHLY_BUDGET::NUMBER(18,2) AS MONTHLY_BUDGET,

    DATASOURCE,
    DATASOURCE_SHEET,
    LOAD_DATE

FROM EXAMPLE.STG.STG_MONTHLY_BUDGET_WIDE
UNPIVOT (
    MONTHLY_BUDGET FOR MONTH_NAME IN (
        JAN, FEB, MAR, APR, MAY, JUN,
        JUL, AUG, SEP, OCT, NOV, DEC
    )
);




CREATE OR REPLACE VIEW EXAMPLE.STG.STG_PAID_MEDIA_ISSUES AS
SELECT
    *,
    CASE
        WHEN "DATE" IS NULL THEN 'Missing report date'
        WHEN CLIENT IS NULL THEN 'Missing client'
        WHEN CAMPAIGN_NAME IS NULL THEN 'Missing campaign name'
        WHEN PLATFORM IS NULL THEN 'Missing platform'
        WHEN SPEND < 0 THEN 'Negative spend'
        WHEN IMPRESSIONS < 0 THEN 'Negative impressions'
        WHEN CLICKS < 0 THEN 'Negative clicks'
        WHEN CLICKS > IMPRESSIONS THEN 'Clicks greater than impressions'
        ELSE NULL
    END AS ISSUE_REASON
FROM EXAMPLE.STG.STG_PAID_MEDIA
WHERE
    "DATE" IS NULL
    OR CLIENT IS NULL
    OR CAMPAIGN_NAME IS NULL
    OR PLATFORM IS NULL
    OR SPEND < 0
    OR IMPRESSIONS < 0
    OR CLICKS < 0
    OR CLICKS > IMPRESSIONS;


CREATE OR REPLACE VIEW EXAMPLE.STG.STG_MONTHLY_BUDGET_ISSUES AS
SELECT
    *,
    CASE
        WHEN CLIENT IS NULL THEN 'Missing client'
        WHEN CAMPAIGN IS NULL THEN 'Missing campaign'
        WHEN FISCAL_YEAR IS NULL THEN 'Missing fiscal year'
        WHEN MONTHLY_BUDGET < 0 THEN 'Negative monthly budget'
        ELSE NULL
    END AS ISSUE_REASON
FROM EXAMPLE.STG.STG_MONTHLY_BUDGET
WHERE
    CLIENT IS NULL
    OR CAMPAIGN IS NULL
    OR FISCAL_YEAR IS NULL
    OR MONTHLY_BUDGET < 0;