-- Purpose:
-- Creates the Snowflake database, schemas, raw tables, and loader role grants
-- required by the Google Sheets ingestion pipeline.
--
-- RAW tables are the direct warehouse targets for the Python loader.
-- They preserve source-level fields plus workbook/tab lineage columns.



-- CREATE DB, SCHEMA, and TABLES
CREATE DATABASE IF NOT EXISTS EXAMPLE;

CREATE SCHEMA IF NOT EXISTS EXAMPLE.RAW;

CREATE TABLE IF NOT EXISTS EXAMPLE.RAW.CAMPAIGN_TRACKER_RAW (
    LAUNCH_DATE DATE,
    END_DATE DATE,
    NAMING_CONVENTION VARCHAR,
    PLATFORM VARCHAR,
    STATUS VARCHAR,
    OWNER VARCHAR,
    PRIORITY VARCHAR,
    NOTES VARCHAR,
    DATASOURCE VARCHAR,
    DATASOURCE_SHEET VARCHAR,
    LOAD_DATE DATE
);

CREATE TABLE IF NOT EXISTS EXAMPLE.RAW.LEADS_RAW (
    LEAD_DATE DATE,
    CLIENT VARCHAR,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    EMAIL VARCHAR,
    PHONE VARCHAR,
    SOURCE VARCHAR,
    SOURCE2 VARCHAR,
    QUALIFIED VARCHAR,
    REVENUE_ESTIMATE FLOAT,
    ADDRESS VARCHAR,
    DATASOURCE VARCHAR,
    DATASOURCE_SHEET VARCHAR,
    LOAD_DATE DATE
);

CREATE TABLE IF NOT EXISTS EXAMPLE.RAW.PAID_MEDIA_RAW (
    "DATE" DATE,
    CLIENT VARCHAR,
    CAMPAIGN_NAME VARCHAR,
    PLATFORM VARCHAR,
    SPEND FLOAT,
    IMPRESSIONS INT,
    CLICKS INT,
    CTR FLOAT,
    STATUS VARCHAR,
    NOTES VARCHAR,
    DATASOURCE VARCHAR,
    DATASOURCE_SHEET VARCHAR,
    LOAD_DATE DATE
);

CREATE TABLE IF NOT EXISTS EXAMPLE.RAW.MONTHLY_BUDGET_RAW (
    CLIENT VARCHAR,
    FISCAL_YEAR INT,
    CAMPAIGN VARCHAR,
    LAUNCH_DATE DATE,
    END_DATE DATE,
    GROSS_BUDGET FLOAT,
    JAN FLOAT,
    FEB FLOAT,
    MAR FLOAT,
    APR FLOAT,
    MAY FLOAT,
    JUN FLOAT,
    JUL FLOAT,
    AUG FLOAT,
    SEP FLOAT,
    OCT FLOAT,
    NOV FLOAT,
    DEC FLOAT,
    NOTES VARCHAR,
    DATASOURCE VARCHAR,
    DATASOURCE_SHEET VARCHAR,
    LOAD_DATE DATE
);



-- CREATE ROLE
USE ROLE USERADMIN;

CREATE ROLE IF NOT EXISTS PYTHON_LOADER_ROLE;

CREATE USER IF NOT EXISTS PYTHON_LOADER
    LOGIN_NAME = 'PYTHON_LOADER'
    DISPLAY_NAME = 'Python Loader Service User'
    DEFAULT_ROLE = PYTHON_LOADER_ROLE
    DEFAULT_WAREHOUSE = COMPUTE_WH
    DEFAULT_NAMESPACE = EXAMPLE.RAW
    TYPE = SERVICE
    RSA_PUBLIC_KEY = 'example-key'
    COMMENT = 'Service user for Python data loading';

GRANT ROLE PYTHON_LOADER_ROLE TO USER PYTHON_LOADER;

-- GRANT PERMISSIONS
USE ROLE SECURITYADMIN;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE PYTHON_LOADER_ROLE;

GRANT USAGE ON DATABASE EXAMPLE TO ROLE PYTHON_LOADER_ROLE;
GRANT USAGE ON SCHEMA EXAMPLE.RAW TO ROLE PYTHON_LOADER_ROLE;

GRANT SELECT, INSERT, DELETE ON TABLE EXAMPLE.RAW.CAMPAIGN_TRACKER_RAW TO ROLE PYTHON_LOADER_ROLE;
GRANT SELECT, INSERT, DELETE ON TABLE EXAMPLE.RAW.LEADS_RAW TO ROLE PYTHON_LOADER_ROLE;
GRANT SELECT, INSERT, DELETE ON TABLE EXAMPLE.RAW.PAID_MEDIA_RAW TO ROLE PYTHON_LOADER_ROLE;
GRANT SELECT, INSERT, DELETE ON TABLE EXAMPLE.RAW.MONTHLY_BUDGET_RAW TO ROLE PYTHON_LOADER_ROLE;

GRANT SELECT, INSERT, DELETE ON FUTURE TABLES IN SCHEMA EXAMPLE.RAW TO ROLE PYTHON_LOADER_ROLE;

